# GoReleaser v2 configuration
# https://goreleaser.com/
version: 2

# Snapshot configuration for main branch builds
# Formats version as "main-<short-sha>" instead of "0.0.0-SNAPSHOT-<sha>"
snapshot:
  version_template: "main-{{ .ShortCommit }}"

before:
  # https://goreleaser.com/customization/hooks/
  hooks:
    - go mod tidy

builds:
  # Skip binary builds - Dockerfile builds from source
  # We only ship Docker images, not standalone binaries
  - skip: true

# Disable archives since we're not building binaries
archives:
  - id: dummy
    files:
      - none*  # No files to archive

dockers:
  # Local image only used for `make docker-build`
  - image_templates: ["{{ .Env.IMG }}"]
    dockerfile: Dockerfile
    use: buildx
    skip_push: true
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - internal/
      - pkg/
      - config/

  # Release/Snapshot - AMD64
  # For releases: tags as v0.1.0-amd64
  # For snapshots: tags as main-<sha>-amd64
  - image_templates:
      - "ghcr.io/nextdoor/{{ .ProjectName }}:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    goarch: amd64
    use: buildx
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - internal/
      - pkg/
      - config/
    build_flag_templates:
      - --platform=linux/amd64
      - --cache-from=type=gha
      - --cache-to=type=gha,mode=max
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Kubernetes controller for real-time AWS cost visibility
      - --label=org.opencontainers.image.url=https://github.com/nextdoor/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/nextdoor/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

  # Release/Snapshot - ARM64
  # For releases: tags as v0.1.0-arm64v8
  # For snapshots: tags as main-<sha>-arm64v8
  - image_templates:
      - "ghcr.io/nextdoor/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - internal/
      - pkg/
      - config/
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --cache-from=type=gha
      - --cache-to=type=gha,mode=max
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Kubernetes controller for real-time AWS cost visibility
      - --label=org.opencontainers.image.url=https://github.com/nextdoor/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/nextdoor/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

docker_manifests:
  # Multi-arch manifest with version/snapshot tag
  # For releases: ghcr.io/nextdoor/lumina:v0.1.0
  # For snapshots: ghcr.io/nextdoor/lumina:main-<sha>
  - name_template: ghcr.io/nextdoor/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/nextdoor/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/nextdoor/{{ .ProjectName }}:{{ .Version }}-arm64v8

  # Latest tag - only for actual releases, not snapshots
  - name_template: ghcr.io/nextdoor/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/nextdoor/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/nextdoor/{{ .ProjectName }}:{{ .Version }}-arm64v8
    skip_push: auto  # Skip for snapshots

  # Main tag - only for snapshots from main branch
  - name_template: ghcr.io/nextdoor/{{ .ProjectName }}:main
    image_templates:
      - ghcr.io/nextdoor/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/nextdoor/{{ .ProjectName }}:{{ .Version }}-arm64v8

# https://goreleaser.com/customization/changelog/
changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Testing
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999
