# GoReleaser v2 configuration for AMD64 builds
# https://goreleaser.com/
version: 2

# Snapshot configuration for main branch builds
snapshot:
  version_template: "main-{{ .ShortCommit }}"

before:
  hooks:
    - go mod tidy

builds:
  # Skip binary builds - Dockerfile builds from source
  - skip: true

archives:
  - id: dummy
    files:
      - none*

dockers:
  # AMD64 image with architecture suffix
  - image_templates:
      - "ghcr.io/nextdoor/{{ .ProjectName }}:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - internal/
      - pkg/
      - config/
    build_flag_templates:
      - --platform=linux/amd64
      - --cache-from=type=gha
      - --cache-to=type=gha,mode=max
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Kubernetes controller for real-time AWS cost visibility
      - --label=org.opencontainers.image.url=https://github.com/nextdoor/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/nextdoor/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

# Disable changelog, release notes, announcements for platform-specific builds
changelog:
  disable: true
announce:
  skip: "true"
