# GoReleaser v2 configuration
# https://goreleaser.com/
version: 2

# Snapshot configuration for main branch builds
# Formats version as "main-<short-sha>" instead of "0.0.0-SNAPSHOT-<sha>"
snapshot:
  version_template: "main-{{ .ShortCommit }}"

before:
  # https://goreleaser.com/customization/hooks/
  hooks:
    - go mod tidy

builds:
  # Skip binary builds - Dockerfile builds from source
  # We only ship Docker images, not standalone binaries
  - skip: true

# Disable archives since we're not building binaries
archives:
  - id: dummy
    files:
      - none*  # No files to archive

dockers:
  # Local image only used for `make docker-build`
  # Kept in old format since IMG env var and skip_push work differently in v2
  - image_templates: ["{{ .Env.IMG }}"]
    dockerfile: Dockerfile
    use: buildx
    skip_push: true
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - internal/
      - pkg/
      - config/

dockers_v2:
  # CI builds - multi-platform with automatic manifest creation
  # For releases: ghcr.io/nextdoor/lumina:v0.1.0, :latest
  # For snapshots: ghcr.io/nextdoor/lumina:main-<sha>, :main
  - ids: []  # No pre-built binaries
    images:
      - "ghcr.io/nextdoor/{{ .ProjectName }}"
    tags:
      - "{{ .Version }}"  # v0.1.0 for releases, main-<sha> for snapshots
      - "{{ if not .IsSnapshot }}latest{{ end }}"  # Only for releases
      - "{{ if .IsSnapshot }}main{{ end }}"  # Only for snapshots
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - internal/
      - pkg/
      - config/
    build_args:
      BUILDKIT_CACHE_FROM: "type=gha"
      BUILDKIT_CACHE_TO: "type=gha,mode=max"
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "Kubernetes controller for real-time AWS cost visibility"
      "org.opencontainers.image.url": "https://github.com/nextdoor/{{ .ProjectName }}"
      "org.opencontainers.image.source": "https://github.com/nextdoor/{{ .ProjectName }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ time \"2006-01-02T15:04:05Z07:00\" }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.licenses": "Apache-2.0"

# https://goreleaser.com/customization/changelog/
changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Testing
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999
